<!DOCTYPE html>
<html lang="de-DE">
<head>
    <title><?= $this->renderBlock('title', 'Default title'); ?></title>
    <meta charset="utf-8">
    <?=  $this->assetList('css'); ?>
</head>
<body>

    <section id="mainWrapper">

        <?php require_once 'header.phtml'; ?>

        <?php require_once 'menu.phtml'; ?>

        <section id="mainContent">
            <article class="width-full">
                <?= $this->renderBlock('content'); ?>
            </article>
            <div class="clear-both"></div>
        </section>

        <footer>

            <div class="container width-full">
                <div class="row">
                    <div class="cell">
                        <h4>Contact box</h4>
                    </div>
                    <div class="cell">
                        <h4>Quicklinks</h4>
                    </div>
                    <div class="cell">
                        <h4>Disclaimer</h4>
                    </div>
                </div>
            </div>

        </footer>

    </section>

    <?= $this->assetList('js'); ?>

</body>
</html>