<?php /** @var \Faulancer\View\GenericViewHelper $v */ ?>
<!DOCTYPE html>
<html lang="de-DE">
<head>
    <title><?= $v->renderBlock('title', 'Default title'); ?></title>
    <meta charset="utf-8">
    <?php echo  $v->getAssets('css'); ?>
</head>
<body>

    <section id="mainWrapper">

        <?php require_once 'header.phtml'; ?>

        <menu id="menuContainer">
            <ul>
                <li><a href="<?= $v->route('homepage'); ?>">Homepage</a></li>
                <li><a href="<?= $v->route('categories'); ?>">Categories</a></li>
                <li><a href="<?= $v->route('contact'); ?>">Contact</a></li>
            </ul>
            <div class="clear-both"></div>
        </menu>

        <section id="mainContent">
            <article>
                <?= $v->renderBlock('content'); ?>
            </article>

            <aside>
                <?= $v->renderBlock('aside'); ?>
            </aside>
            <div class="clear-both"></div>
        </section>

        <footer>

            <div class="container width-full">
                <div class="row">
                    <div class="cell">
                        <h4>Contact box</h4>
                    </div>
                    <div class="cell">
                        <h4>Quicklinks</h4>
                    </div>
                    <div class="cell">
                        <h4>Disclaimer</h4>
                    </div>
                </div>
            </div>

        </footer>

    </section>

</body>
</html>