<?php /** @var \Faulancer\View\GenericViewHelper $v */ ?>
<!DOCTYPE html>
<html lang="de-DE">
<head>
    <title><?= $this->renderBlock('title', 'Default title'); ?></title>
    <meta charset="utf-8">
    <?= $this->assetList('css'); ?>
</head>
<body>

    <?php require_once 'menu.phtml'; ?>

    <?php require_once 'slider.phtml'; ?>

    <section class="mainWrapper">

        <section id="mainContent">
            <article>
                <?= $this->renderBlock('content'); ?>
            </article>

            <aside>
                <?= $this->renderBlock('aside'); ?>
            </aside>
            <div class="clear-both"></div>
        </section>

        <footer>

            <div class="container width-full">
                <div class="row">
                    <div class="cell">
                        <h4>Contact box</h4>
                    </div>
                    <div class="cell">
                        <h4>Quicklinks</h4>
                    </div>
                    <div class="cell">
                        <h4>Disclaimer</h4>
                    </div>
                </div>
            </div>

        </footer>

    </section>

    <?= $this->assetList('js'); ?>

</body>
</html>