<section id="mainInfo">

    <div class="stage block" aria-hidden="true">
        <i class="fa fa-mobile fa-3x"></i>
        <i class="fa fa-tablet fa-3x"></i>
        <i class="fa fa-desktop fa-3x"></i>
        <div class="text">No obstacles for devices</div>
        <div class="further-information">
            <ul>
                <li>Output in JSON, XML or Text</li>
                <li>RESTful controller included</li>
                <li>No device dependencies</li>
                <li>Minimal configuration needed</li>
            </ul>
        </div>
    </div>
    <div class="stage block">
        <i class="fa fa-github fa-3x"></i>
        <span class="text">Open source (MIT License)</span>
        <div class="further-information">
            <ul>
                <li>Completely free</li>
                <li>Feature ideas are welcome</li>
                <li>Own features are appreciated</li>
            </ul>
        </div>
    </div>

    <div class="stage block">
        <i class="fa fa-check fa-3x"></i>
        <span class="text">Continuously maintained</span>
        <div class="further-information">
            <ul>
                <li>Automated builds</li>
                <li>Tested with PHPUnit</li>
                <li>Minimized dependencies</li>
                <li>Maximized performance</li>
                <li>100% code coverage</li>
            </ul>
        </div>
    </div>

    <div class="stage block">
        <i class="fa fa-code fa-3x"></i>
        <span class="text">Usage of proven concepts</span>
        <div class="further-information">
            <ul>
                <li>Everything is a service</li>
                <li>Template inheritance</li>
                <li>Enhanced debug output</li>
                <li>View helper within $this</li>
                <li>Fast and easy ORM included</li>
            </ul>
        </div>
    </div>
    <div class="clear-both"></div>
</section>

<hr>