<?php
/**
 * @var \App\Entity\ArticleEntity $article
 */ ?>
<?php $this->parentTemplate('/layout.phtml'); ?>

<?php $this->block('title'); ?>
<?= $article->title; ?>
<?php $this->endBlock('title'); ?>

<?php $this->block('content'); ?>

<h1><?= $article->title; ?></h1>
<h5>Author: <?= $article->author->firstname . ' ' . $article->author->lastname; ?></h5>
<h5>Category: <?= $article->category->name; ?></h5>


<p><?= $article->text; ?></p>

<?php $this->endBlock('content'); ?>
