<?php
/**
 * @var \Faulancer\View\GenericViewHelper $v
 * @var \App\Entity\ArticleEntity $article
 */ ?>
<?php $v->extendsTemplate('/layout.phtml'); ?>

<?php $v->block('title'); ?>
<?= $article->title; ?>
<?php $v->block(); ?>

<?php $v->block('content'); ?>

<h1><?= $article->title; ?></h1>
<h5>Author: <?= $article->author->firstname . ' ' . $article->author->lastname; ?></h5>
<h5>Category: <?= $article->category->name; ?></h5>


<p><?= $article->text; ?></p>

<?php $v->block(); ?>
