<?php
/**
 * @var \App\Entity\ArticleEntity[] $articles
 * @var \App\Entity\CategoryEntity  $category
 */
?>
<?php $this->parentTemplate('/layout_full.phtml'); ?>

<?php $this->block('title'); ?>
Category <?= $category->name; ?>
<?php $this->endBlock('title'); ?>

<?php $this->block('content'); ?>

    <h1><?= $category->name; ?></h1>

<?php foreach ($articles as $article): ?>

    <a class="box-item" href="<?= $this->route('article', [$article->id]) ?>"><?= $article->title; ?></a>

<?php endforeach; ?>

<?php $this->endBlock('content'); ?>