<?php
/**
 * @var \Faulancer\View\GenericViewHelper $v
 * @var \App\Entity\CategoryEntity[] $categories
 * @var \App\Entity\CategoryEntity   $category
 */ ?>
<?php $v->extendsTemplate('/layout.phtml'); ?>

<?php $v->block('title'); ?>

<?php $v->block(); ?>

<?php $v->block('content'); ?>

    <h1>Categories</h1>

    <?php foreach ($categories as $category): ?>

        <a href="<?= $v->route('category', [$category->id]) ?>"><?= $category->name; ?></a><br />

    <?php endforeach; ?>

<?php $v->block(); ?>
