<?php
/**
 * @var \App\Entity\CategoryEntity[] $categories
 * @var \App\Entity\CategoryEntity   $category
 */ ?>
<?php $this->parentTemplate('/layout.phtml'); ?>

<?php $this->block('title'); ?>
Categories
<?php $this->endBlock('title'); ?>

<?php $this->block('content'); ?>

    <h1>Categories</h1>

    <?php foreach ($categories as $category): ?>

        <a href="<?= $this->route('category', [$category->id]) ?>"><?= $category->name; ?></a><br />

    <?php endforeach; ?>

<?php $this->endBlock('content'); ?>
