<?php
/**
 * @var \Faulancer\View\GenericViewHelper $v
 * @var \App\Entity\ArticleEntity[] $articles
 * @var \App\Entity\CategoryEntity  $category
 */
?>
<?php $v->extendsTemplate('/layout.phtml'); ?>

<?php $v->block('content'); ?>

    <h1><?= $category->name; ?></h1>

<?php foreach ($articles as $article): ?>

    <a href="<?= $v->route('article', [$article->id]) ?>"><?= $article->title; ?></a><br />

<?php endforeach; ?>

<?php $v->block(); ?>