<?php $this->parentTemplate('/layout.phtml'); ?>

<?php $this->block('title'); ?>
Landingpage
<?php $this->endBlock('title'); ?>

<?php $this->block('content'); ?>

<h1>The main content</h1>

This is the main landingpage, which will see everyone on his first visit. Due to the flexibility you can handle and
design each site completely independent. You can even set the page title through this template.

<hr>

<?php /** @var \stdClass|countable $recentArticles */ ?>
<h3>Articles (<?= count($recentArticles); ?>)</h3>

<?php foreach ($recentArticles as $article): ?>


    <div class="article-short">
        <a href="<?= $this->route('article', ['id' => $article->id]); ?>">
        <?php
            echo '<h4>' . $article->title . '<span class="article-date-created">' . (new \DateTime($article->created))->format('d.m.Y, H:i') . '</span></h4>';
            echo '<p>' . $article->text . '</p>';
        ?>
        </a>
    </div>


<?php endforeach; ?>

<?php $this->endBlock('content'); ?>

<?php $this->block('aside'); ?>

<h2>The aside content</h2>

This is the side content which can be filled with various elements, like login boxes,
newsflash boxes or the not unlikely ad container.

<hr>

<h3>Most read articles</h3>

<?php /** @var \stdClass $mostReadArticles */ ?>
<?php foreach ($mostReadArticles as $article): ?>

    <div class="article-short">
        <?php
            echo '<h4>' . $article->title . '<span class="article-date-created">' . (new \DateTime($article->created))->format('d.m.Y, H:i') . '</span></h4>';
            echo '<p>' . $article->text . '</p>';
        ?>
    </div>

<?php endforeach; ?>

<?php $this->endBlock('aside'); ?>
